---
- name: Initialize Kubernetes control plane
  ansible.builtin.command: kubeadm init --apiserver-advertise-address=192.168.60.10 --pod-network-cidr=10.244.0.0/16
  args:
    creates: /etc/kubernetes/admin.conf

- name: Create .kube directory
  ansible.builtin.file:
    path: /home/vagrant/.kube
    state: directory
    owner: vagrant
    group: vagrant
    mode: '0755'

- name: Copy admin kubeconfig
  ansible.builtin.copy:
    src: /etc/kubernetes/admin.conf
    dest: /home/vagrant/.kube/config
    remote_src: true
    owner: vagrant
    group: vagrant
    mode: '0644'

- name: Wait for Kubernetes API server
  ansible.builtin.command: kubectl --kubeconfig /etc/kubernetes/admin.conf get nodes
  register: kubectl_ready
  retries: 20
  delay: 10
  until: kubectl_ready.rc == 0
  changed_when: false