---
- name: Get join command from control plane
  ansible.builtin.command: kubeadm token create --print-join-command
  register: kubernetes_join_command
  delegate_to: "{{ groups['kubernetes_control_plane'][0] }}"

- name: Join worker to cluster
  ansible.builtin.command: "{{ kubernetes_join_command.stdout }}"
  args:
    creates: /etc/kubernetes/kubelet.conf