# This is the Ansible inventory file for the Kubernetes lab environment.
# wsl user should ne exported in a file config
# copying the keys to wsl should also be move to almalinux10wsl or vagrant
# ansible_ssh_private_key_file: /home/tosshs/.ssh/vagrant-kubernetes-lab/control-plane
# ansible_ssh_private_key_file: /home/tosshs/.ssh/vagrant-kubernetes-lab/worker

---
all:
  children:
    kubernetes_control_plane:
      hosts:
        kubernetes-lab-control-plane:
          ansible_host: 192.168.60.10
          ansible_user: vagrant
          ansible_ssh_private_key_file: /home/tosshs/.ssh/vagrant-kubernetes-lab/control-plane

    kubernetes_workers:
      hosts:
        kubernetes-lab-worker:
          ansible_host: 192.168.60.20
          ansible_user: vagrant
          ansible_ssh_private_key_file: /home/tosshs/.ssh/vagrant-kubernetes-lab/worker

    registry:
      hosts:
        kubernetes-lab-preg:
          ansible_host: 192.168.60.30
          ansible_user: vagrant
          ansible_ssh_private_key_file: /home/tosshs/.ssh/vagrant-kubernetes-lab/preg

    kubernetes_cluster:
      children:
        kubernetes_control_plane:
        kubernetes_workers: