apiVersion: v1
kind: Pod
metadata:
  name: kube-controller-manager
  namespace: kube-system
spec:
  containers:
    - name: kube-controller-manager
      livenessProbe:
        failureThreshold: 8
        initialDelaySeconds: 90
        periodSeconds: 60
        timeoutSeconds: 15
      startupProbe:
        failureThreshold: 24
        initialDelaySeconds: 90
        periodSeconds: 60
        timeoutSeconds: 15